services:
  - type: web
    name: hackathon-spare-change
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: COINBASE_API_BASE_URL
        value: https://api-public.sandbox.exchange.coinbase.com
      - key: COINBASE_API_KEY
        value: c8e3dd047d8ba2b69d95c08855a6fa1c
      - key: COINBASE_API_SECRET
        value: 0zNKGVp6xuBt+Rc7i/DiwBGO2zENc6Tv4L3x6aMT/0zGwxnKuvqg2s59bJtlgRk5PxJmbKYEY6zu4WCJk75LRw==
      - key: COINBASE_API_PASSPHRASE
        value: bu6rg4hlfol6