spring:
  application:
    name: spare-change-api
  
  datasource:
    url: jdbc:h2:mem:sparechangedb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    
coinbase:
  api:
    base-url: https://api-public.sandbox.exchange.coinbase.com
    buy-threshold: 5.00
    key: 9530995e3dd6efc84b3ebf292d1b4c4a
    secret: bALCwmqaWEkP8fKG0EkbTHu6NBs6AHYbuHrJ8na0gJgfKlxkIyjtrtoCNsTRLXVIexN0g/mDsaohUeyW5ReaKg==
    passphrase: 3d8i245ycg8q

stacker:
  delay:
    mas: 300000  # 5 minutes in milliseconds